#!/bin/bash

# Indirizzo IP base della rete
base_ip="192.168.1."

# Range di IP da verificare
start=1
end=255

# Nome utente SSH
username="pi"

# Comando SSH per la verifica
ssh_command="ssh -o ConnectTimeout=2 $username@"

# Iterazione attraverso gli indirizzi IP
for ((i=start; i<=end; i++))
do
  ip="$base_ip$i"
  echo "Provo l'indirizzo IP: $ip"
  
  # Esegui il comando SSH per verificare la connessione
  if $ssh_command$ip exit >/dev/null 2>&1; then
    echo "Trovato! Indirizzo IP valido: $ip"
    # Puoi eseguire ulteriori comandi sulla Raspberry Pi qui, se necessario
    break
  else
    echo "Non valido."
  fi
done
